import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./store/ReduxProvider";
import { ThemeProvider } from "@/components/ThemeProvider";
import { supabase } from "@/config/db";
import { ToastContainer } from "@/components/ui/Toast";
import { SessionManager } from "@/components/auth/SessionManager";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch global theme from DB
  let globalTheme = "system";
  try {
    const { data: settings } = await supabase
      .from("app_settings")
      .select("theme, enable_global_theme")
      .limit(1)
      .single();
      
    if (settings) {
      if (settings.enable_global_theme && settings.theme) {
        globalTheme = settings.theme;
      } else {
        globalTheme = "system";
      }
    }
  } catch (err) {
    // Fail silently, use system default
  }

  // Pre-calculate class to prevent flicker
  let htmlClass = "";
  if (globalTheme === "dark") htmlClass = "dark";
  if (globalTheme === "light") htmlClass = "light";
  
  return (
    <html lang="en" suppressHydrationWarning className={htmlClass}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider defaultTheme={globalTheme as any}>
          <ReduxProvider>
            <SessionManager>
              {children}
              <ToastContainer />
            </SessionManager>
          </ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
